# Generated by Django 6.0.3 on 2026-04-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TenantModel',
        ),
    ]
