# Generated by Django 6.0.3 on 2026-04-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_oragnization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='oragnization',
            new_name='organization',
        ),
    ]
