# Generated by Django 6.0.3 on 2026-04-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_comment_oragnization_ticket_oragnization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='oragnization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='oragnization',
            new_name='organization',
        ),
    ]
