# Generated by Django 6.0.3 on 2026-04-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_oragnization_comment_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('comment', 'Комментарий'), ('close_comment', 'Комментарий при закрытии'), ('cancel_comment', 'Комментарий при отмене'), ('resolve_comment', 'Комментарий при решении')], default='comment', max_length=15),
        ),
    ]
