# Generated by Django 6.0.3 on 2026-04-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_comment_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('comment', 'Комментарий'), ('close_comment', 'Комментарий при закрытии'), ('cancel_comment', 'Комментарий при отмене'), ('resolve_comment', 'Комментарий при решении'), ('reopen_comment', 'Комментарий при возобновлении')], default='comment', max_length=15),
        ),
    ]
