# Generated by Django 6.0.3 on 2026-05-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('comment', 'Комментарий'), ('close_comment', 'Комментарий при закрытии'), ('cancel_comment', 'Комментарий при отмене'), ('resolve_comment', 'Комментарий при решении'), ('reopen_comment', 'Комментарий при возобновлении'), ('assign_comment', 'Комментриай при назначении'), ('unassign_comment', 'Комментарий при снятии с назначения')], default='comment', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
