# Generated by Django 6.0.3 on 2026-05-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_comment_comment_type_alter_ticket_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('1', 'Низкий'), ('2', 'Обычный'), ('3', 'Средний'), ('4', 'Высокий'), ('5', 'Критический')], default='2', max_length=10),
        ),
    ]
