# Generated by Django 6.0.3 on 2026-03-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Тип конфигурационной единицы',
                'verbose_name_plural': 'Типы конфигурационной единицы',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('maintenance', 'Обслуживание'), ('retired', 'Выведен')], default='active', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('asset_tag', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ci_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_items', to='cmdb.citype')),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='cmdb.configurationitem')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmdb.configurationitem')),
            ],
            options={
                'verbose_name': 'Конфигурационная единица',
                'verbose_name_plural': 'Конфигурационные единицы',
                'ordering': ['name'],
            },
        ),
    ]
