# Generated by Django 6.0.3 on 2026-04-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
        ('core', '0002_delete_tenantmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationitem',
            name='oragnization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization'),
            preserve_default=False,
        ),
    ]
