# Generated by Django 6.0.3 on 2026-04-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_configurationitem_oragnization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationitem',
            old_name='oragnization',
            new_name='organization',
        ),
    ]
