# Generated by Django 6.0.3 on 2026-05-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_alter_configurationitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationitem',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='configurationitem',
            name='parent',
        ),
    ]
