# Generated by Django 6.0.3 on 2026-05-25 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_remove_configurationitem_dependencies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_child', to='cmdb.configurationitem')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_parent', to='cmdb.configurationitem')),
            ],
            options={
                'verbose_name': 'Зависимость конфигурационных единиц',
                'verbose_name_plural': 'Зависимости конфигурационных единиц',
            },
        ),
    ]
