# Generated by Django 6.0.3 on 2026-05-25 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_cidependency'),
        ('core', '0002_delete_tenantmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidependency',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization'),
            preserve_default=False,
        ),
    ]
